spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carleasedb
    username: carleaseuser
    password: carleasepwd
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8080
token:
  signing:
    key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437


